# Bare keys
key = "value"
bare_key = "value"
bare-key = "value"
1234 = "value"

# Quoted keys
"127.0.0.1" = "value"
"character encoding" = "value"
"ʎǝʞ" = "value"
'key2' = "value"
'quoted "value"' = "value"

# Dotted keys
name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
